apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/uruguruu/enpassant/enpassant-frontend:latest
          env:
            - name: APIURL
              value: "http://127.0.0.1:3004"
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
      volumes:
        - name: config-volume
          configMap:
            name: app-config